project:
  type: website

  preview: 
    port: 3333
    browser: true
    watch-inputs: true
    navigate: true
  
  resources:
    - "files/**"

# website metadata values
description-meta: "Personal website with blogs on academia and social 
science research."

website:
  title: "Dr Beth Jones"
  repo-url: https://github.com/bethjonesresearch/website
  navbar:
  logo: #TODO
    pinned: true

    left:
    - text: "Home"
      href: "index.qmd"
    - text: "CV"
      href: #TODO
    - text: "Publications"
      href: #TODO
    - text: "Blog"
      href: "blog/index.qmd"
    - text: "Contact"
      href: #TODO

  page-footer:
    border: true
    left: |
      This site is built using [![](https://quarto.org/quarto.png){fig-alt="quarto" width=80px}](https://quarto.org)
    left: |
      Any opinions expressed are my own. [Report an issue](https://github.com/bethjonesresearch/website/issues) on GitHub.


format: 
  html:
  css: files/styles.css
  theme:
    - flatly
    - files/ #TODO