Qualitative research interviews and 15 minutes of panic


#### Disclaimer
I first wrote this blog draft back in 2022, and it has been edited and resurrected for this version of my site. If you've been a reader for a while this means you've likely read this before. I hope it's just as useful this time around!


As a researcher I spend big chunks of my time in work interviewing people about their thoughts and experiences to collect data for studies. I don’t have an exact number, but I do know that I’ve done well over 100 of these interviews so far in my career. I’ve had enough experience to be able to recognise some patterns in my thoughts and feelings when I do interview someone. An interview is the type of conversation where your focus needs to be in a few different places at once: 
1. First, it needs to be in the moment, listening to what your participant is saying so that you can ask thoughtful and relevant questions to unpick their experiences or perspectives. You also want to be sure that the participant knows you are listening and respect the time they have given to share their experiences with you. 


2. Second, your brain is holding what people have told you in the conversation already, so that you can come back to it later in the interview if you want. You may be using an interview schedule with semi-structured interviews so may be mentally holding this up against a virtual timeline.


3.You might also be thinking long-term during this conversation, about whether this data collection is in line with literature you’ve read on the topic and whether it seems like it might answer your research questions when you do the analysis. Interviewing research participants is a skill, and I found it took practice to learn to hold all of this in my head at once and still ask thoughtful and explorative questions to open up the discussion and generate rich qualitative data. 


4. I also know that I have an extra layer of thought going on when I am collecting research data using interviews, and it becomes especially prominent in my attention during minutes 15-30 of interview data collection. I’ve talked about this phenomenon with a few other qualitative researchers, some identified with this experience, and some didn’t. I’ve decided to talk about it (and the strategies I use to manage it). I hope it helps other people collecting interview data.













SO

I have an irrational discomfort of minutes 15-30 when collecting interview data. I’ve tried to unpick it. It is built around the idea that I will start the interview smoothly, break the ice with some opening questions to start the discussion and then for no real reason at all, the participant and I will run out of stuff to talk about, and the interview will be cut short in a really awkward way. I have to hold an extra block of worry in my head here about whether the data I’m collecting is rich enough and whether I’m doing a good enough job as an interviewer to help the participant feel able to talk and share enough of their experience with me to generate “good” data. This is irrational. I know it is irrational because:


1. There’s nothing actually wrong with an interview being short. Qualitative research is interested in depth and richness of data, not how long it took for you to collect it. This is based on an incorrect assumption of some unconscious part of my brain that a longer interview = better. Sometimes it isn’t, and shorter interviews are necessary for practical reasons. For example, it would not be ethical as a researcher to conduct overly long interviews with people with health conditions that mean that a 1-hour interview with me would leave them fatigued and drained for several days afterwards. People might also be busy but with valuable expertise that can really help a research study and so can only spare 15-20 minutes of their time for an interview. 



2. Sometimes an interview might be short, but we cover all we need in that time. Longer interviews don’t guarantee rich data. 
Despite my fear of running out of stuff to talk about, there is usually an interview schedule there to guide discussion. There’s no pressure for participants to talk for so long that we run for over 30 minutes, but there will likely be some kind of list of questions or topic guide there for me to rely on. I most commonly collect data using semi-structured interviews so ask questions or discuss things that are not on the interview schedule, and this is common. This means that I’ve got plenty available to me to ask about during minutes 15 to 30, or I can pick up threads that the participant started talking about and ask them to tell me more. 


3. Crucially, this “running out of stuff to talk about” hasn’t happened to me before. A participant and I tend to get talking when we start the interview and set the scene and move our way through our “conversation with a purpose” easily. People tend to choose to take part in research that relates to them, or that they are interested in and this tends to mean that they have stuff to say on the topic.  This will help, and this will benefit you. 

I find that once my interview hits the 30-minute mark I tend to relax. Paradoxically and so predictably, my interview technique is always better, and the interview flows more comfortably. I feel more relaxed and more able to get the best out of my participants because I’m more in the moment, more responsible to the little things they tell me that I want to know more about, and more able to actively listen. Even though I know this, every single time I do an interview, I worry during minutes 15-30. 


So what to do about this? 


For those who may also struggle with worrying about their data collection actually getting in the way of their data collection, I’ve picked up a few techniques along the way to help!
1. When I start recording, I cover the time up for a little while. It’s important to be respectful of participants’ time and not overrun, but I feel more relaxed when I cover the clocks for a little while to start. This involves flipping my Dictaphone screen down once I’ve checked it’s recording, and sometimes using a sticky note on my computer clock to stop me peeking. I have to remove this at some point during the interview to be sure that I haven’t taken up too much of the participants’ time but not being able to see it all the time takes some of the struggle out of it. 


2. Where I can, I pilot my interview schedule with a colleague and ask them to be deliberately vague so I can figure out where my “unpicking points” are, where I might ask them to expand or tell me more on specific questions to understand more about the topic and their experiences.


3. I have a few questions on my interview schedule highlighted as “minutes 15-30” questions, so once we’ve broken the ice, I know it’ll open up discussion of the topic.


4. Sitting with the knowledge that the data I collect will be ok, and that the experiences that participants share will tell me something meaningful in some way, and that’s always appreciated.

I’d be interested to know other peoples’ experiences of their thoughts and planning when they carry out qualitative research, or if anyone has a similar 15-30 minute problem!