

#### Disclaimer
I first wrote this blog draft back in 2022, and it has been edited and resurrected for this version of my site. If you've been a reader for a while this means you've likely read this before. I hope it's just as useful this time around!

This post is brought to you by the current UK heatwave, and the number of people I've spoken to who just don't have the concentration to do much at all. When you're having an "off" day, or you haven't slept, or something is on your mind, or you're burned out or overwhelmed it can feel even more pressured to deliver on doing something. Anything! 



When I speak to graduate students who are finding their way through their PhD, the most 


important piece of advice I am keen to pass on is one I learned quite early into my doctorate because of luck, not out of good practice on my part. 2 months into my PhD I was concussed and my concentration, focus, and working memory were affected for several months after. I found that sometimes I would wake up and I could concentrate for a whole work day without a problem. Sometimes I would wake up and have about 30 good minutes in me, or 2 hours, or 10 minutes. 



I learned that on those days when my brain just didn't come to join me that it just wasn't worth the fight. I could do whatever it was I had capacity to do and then stop and go home/watch tv/go on my bike, or I could push through and beat myself up sitting at my desk for 8 more hours trying and trying and trying to get stuff done and I often wouldn't have much to show for it. Maybe a few extra sentences, or one more paper read, or a handful of emails. Nothing to justify the mental effort and psychological "ick" from telling myself I wasn't doing enough or I was failing at my job that day. If the focus and concentration wasn't there that day, the rest was worth way more than those extra few sentences or emails. The permission from myself to stop and rest, rather than pay that exhaustion forward to the next day and cause a cycle of bad days was crucial to learning how to keep going through the PhD process. It's not that I didn't want to work, it was often that my brain just wouldn't let me.



This became a similar problem at early points during the COVID-19 pandemic, when everything felt worrying or frightening. More recently I've also had a flare of my long-term condition that means my energy levels have been drained by fatigue. In these circumstances, I'm hired to work a specific number of hours. While I'm lucky enough to have flexibility with my time so I can work more hours on good days and fewer hours on bad days, I've started keeping a list of "bad day activities" that don't require as much concentrated effort but still contribute to me doing my job well.



Some of the items on this list are:





Organising my referencing software: archiving anything I no longer use, filling in gaps in references so that they don't cause errors when I cite papers, and adding papers from my ResearchGate or Google Scholar "saved folder" into a specific "READ ME NEXT" folder in my reference manager.



Similarly, archiving and reviewing my emails to keep space in my inbox without losing anything I need to store as part of my documentation requirements. This also helps me catch things I may have missed and add them to my upcoming to-do list.



Listening to work-related podcasts to reduce screen-time for my eyes while taking in useful information. I have a few academic skills related podcasts (including Prof Mark Reed's excellent "Fast Track Impact" podcast covering research impact and knowledge translation (here) and Prof Inger Mewburn and Dr Jason Downs' "On the Reg"  that discusses life in academia and productivity hacks to reclaim  time for what matters, including ice cream in the sun (here). 



On that thread, I also keep a list of podcasts and youtube videos related to my work topic to review. Videos are becoming an increasingly common means of sharing findings and I've learned a great deal about my current topic of primary care staffing skill mix from registered bodies and local NHS care boards' youtube channels. I find I often have more focus for videos on bad days than reading from a screen, so will often have my computer read aloud to me if I do choose to read work on an off day.



Sometimes active thinking but for shorter bursts of time is a good way to spend my energy on an off day, because it concentrates my efforts on what interests me and where I would like to be with my goals in the future. I often use this time to map out research directions I'm interested in, papers I plan to write based on my "writing backlog", or public engagement activities I'd be keen to try in the future. This often has the unintended consequence of energising me and leaving my feeling positive about my day, even if it started as a tricky one.



Shortening my pomodoros (see my description of these here) to 3 minutes of work, 2 minutes of rest. It sounds like a really small amount of work, but it was sometimes the best way of starting something if I knew I only needed to focus for 180 seconds as a minumum.



I appreciate that motivation can also be a common cause of an off-day, and plan to write a future blog post covering strategies for motivation struggle in research work. The Fast Track Impact podcast has an excellent 2 part episode on motivation, and On the Reg also covers some techniques that made me laugh but actually do work (including 5-4-3-2-1-GO! Trust me). 



What do you do to stay productive on a day where your focus hasn't come to the desk with you?